### ISSUE TITLE
App doesn't run on android

### ISSUE THREAD

**Issue by syonip** [pichillilorenzo/flutter_browser_app#23]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |         3.24.3      |
| App version          |      3.1.0+9         |
| Android version      |       10        |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:** 
The app doesn't crash on run
**Current behavior:** 
App crashes on run

## Steps to reproduce
Run app on android

## StackTrace:
```
The relevant error-causing widget was:
    ChangeNotifierProxyProvider<WebViewModel, WindowModel> ChangeNotifierProxyProvider:file:///C:/git/flutter_browser_app/lib/main.dart:126:9

When the exception was thrown, this was the stack:
#0      WindowManagerPlus.current (package:window_manager_plus/src/window_manager.dart:60:51)
window_manager.dart:60
#1      _FlutterBrowserAppState.initState (package:flutter_browser/main.dart:152:23)
main.dart:152
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5748:55)
framework.dart:5748
```

**Comment by syonip** [comment]
Also happens on android 15 emulator
